home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='home'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_out', views.sign_out, name='sign_out'),
]

pemesanan/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='pemesanan'

urlpatterns = [
    path('', views.pemesanan, name='pemesanan'),
    path('lihatPemesanan/', views.lihatPemesanan, name='lihatPemesanan'),
]

pertamina/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('pemesanan/', include('pemesanan.urls')),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self,email,password,zipcode,institution_name,shipping_address):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email = self.normalize_email(email),
            zipcode= zipcode,
            institution_name = institution_name,
            shipping_address = shipping_address
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
        
class User(AbstractBaseUser):
    email = models.EmailField(max_length=255,unique=True)
    zipcode = models.IntegerField()
    institution_name = models.CharField(max_length=50)
    shipping_address = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

pemesanan/models.py
from django.db import models
from django.db.models.fields import IntegerField
from pertamina.settings import AUTH_USER_MODEL as User
# Create your models here.

class Bbm(models.Model):
    id = models.AutoField(primary_key=True)
    lokasi = models.CharField(max_length=100)
    jumlah = models.IntegerField()
    tanggal_pengiriman = models.DateField()
    transportir = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import *

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['zipcode', 'institution_name', 'shipping_address','email']

pemesanan/forms.py
from django.db.models import fields
from django.forms.models import ModelForm
from pemesanan.models import Bbm
from django import forms

class BbmForm(ModelForm):
    class Meta:
        model = Bbm
        fields = ['lokasi', 'jumlah', 'tanggal_pengiriman', 'transportir']
        exclude = ('user',)

home/views.py
from django.http import response
from .forms import *
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate, logout
from .models import User

# Create your views here.
def welcome(request):
    return render(request, 'home.html')

def sign_up(request):
    if (request.method == 'POST'):
        form = SignUpForm(request.POST)
        if (form.is_valid()):
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=user.email, password=raw_password)
            login(request, user)
            return redirect('pemesanan:pemesanan')
    return render(request, 'sign_up.html')

def sign_in(request):
    response = {}
    if (request.method == 'POST'):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            request.session['email'] = user.email
            return redirect('pemesanan:pemesanan')
        else:
            response['message'] = 'Username / Password salah'
    return render(request, 'sign_in.html')

def sign_out(request):
    logout(request)
    return redirect('home:welcome')

pemesanan/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *

# Create your views here.
def pemesanan(request):
    if 'email' not in request.session:
        return redirect('home:sign_in')
    
    if(request.method=="POST"):
        form = BbmForm(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('pemesanan:lihatPemesanan')
        else:
            print("gagal")
            form = Bbm()
        
        context = {
            'form': form
            }

    return render(request, 'pemesanan.html')

def lihatPemesanan(request):
    if 'email' not in request.session:
        return redirect('home:sign_in')

    bbm = Bbm.objects.filter(user=request.user)
    context ={
			'bbm' : bbm
		}
    return render(request, 'lihatPemesanan.html', context)

home/templates/home.html
{% extends 'navbar.html' %}
{% load static %}
{% block title %}
<style>
    .container{
margin-top:100px; 
}

</style>
<title>Homepage</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row"> 
                <img style="width: 100%;" src="{% static 'reaktor.jpeg' %}">
            </div>
            <div class="row">
                <img style="width: 100%;" src="{% static 'orang.jpeg' %}">
            </div>
        </div>
        <div class="col">
            <div style="margin:100px 50px">
                <h1 style="margin:30px">Selamat Datang</h1>
                <h5 style="margin:30px">Website resmi pertamina untuk registrasi pembelian BBM industri ke seluruh Indonesia</h5>
                <a style="margin:10px 30px" type="button" class="btn btn-primary" href="{% url 'home:sign_up' %}">Sign Up</a>
            </div>
            
        </div>
      </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock%}

home/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  
    {% block title %}

    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm p-3 mb-5" id="navigation" style='background-color: white;'>
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'Pertamina_Logo.png' %}" alt="" id="logo" style="height: 50px;width: 200px;">
        </a>
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            <a class="nav-link nav-item"  href="#">Help</a>
            <a class="nav-link nav-item" href="#">Contact Us</a>
            <a class="nav-link nav-item" href="{% url 'home:sign_in' %}">Sign In</a>
            <a class="nav-link nav-item" href="{% url 'home:welcome' %}">home</a>
        </div>
    </div>
    </nav>
{% block content %}


{% endblock %}
</body>



</html>

home/templates/sign_in.html
{% extends 'navbar.html' %}
{% load static %}
{% block title %}
<style>
    #signin-container{
margin-top:100px; 
}

</style>
{% endblock %}
{% block content %}
<div id="signin-container">
        <div class="row">
          <div class="col">
            <div style="margin-left: 50px;">
                <form method="POST">
                    {% csrf_token %}
                    <div id="signup-form">
                        <h3>Welcome!</h3>
                        <h4>Don't have account, <a href="{% url 'home:sign_up' %}">Sign Up</a></h4>
                        <div class="form-group">
                            <label>Email</label>
                            <input class="form-control" id="id-password" type="email" name="email" required>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input class="form-control" id="id-password" type="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Daftar</button>
                    </div>
                </form>
            </div>
          </div>
          <div class="col">
            <img src="{% static 'orang2.jpeg'%}" style="width: 100%;height: 100%;">
          </div>
        </div>
</div>
{% endblock%}

home/templates/sign_up.html
{% extends 'navbar.html' %}
{% load static %}
{% block title %}
<style>
    #signup-container{
margin-top:100px; 
}

</style>
{% endblock %}
{% block content %}
<div id="signup-container">
        <div class="row">
            <div class="col">
                <div id="signup-title">
                    <h2 style="margin-left: 50px;">Account Registration</h2>
                </div>
                <div>
                    <hr id="hr-line">
                </div>
                <div style="margin-left: 50px;">
                    <form method="POST">
                        {% csrf_token %}
                        <div id="signup-form">
                            <h4>Institution Info</h4>
                            <h5>Silahkan isi data perusahaan Anda</h5>
                            <div class="form-group">
                                <label>Zip Code</label>
                                <input class="form-control" id="id-name" type="Integer" name="zipcode" required>
                            </div>
                            <div class="form-group">
                                <label>Institution Name</label>
                                <input class="form-control" id="id-email" type="text" name="institution_name" required>
                            </div>
                            <div class="form-group">
                                <label>Shipping Address</label>
                                <input class="form-control" id="id-email" type="text" name="shipping_address" required>
                            </div>
                            <h5>Set up your log in info</h5>
                            <div class="form-group">
                                <label>Email</label>
                                <input class="form-control" id="id-password" type="email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input class="form-control" id="id-password" type="password" name="password1" required>
                            </div>
                            <div class="form-group">
                                <label>Konfirmasi Password</label>
                                <input class="form-control" id="id-password-confirmation" type="password" name="password2" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Daftar</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col">
                <img src="{% static 'kilang3.jpg'%}" style="width: 100%;height: 100%;">
            </div>
        </div>
</div>
{% endblock%}

pemesanan/templates/lihatPemesanan.html
{% extends 'navbar2.html' %}
{% load static %}
{% block title %}
<style>
    #pemesanan-container{
margin-top:100px; 
}

</style>
{% endblock %}
{% block content %}
<div id="pemesanan-container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Lokasi</th>
            <th scope="col">Jumlah</th>
            <th scope="col">Tanggal Pengiriman</th>
            <th scope="col">Transportir</th>
          </tr>
        </thead>
        
        <tbody>
            {% for pesanan in bbm %}
          <tr>
            <td>{{ pesanan.lokasi }}</td>
            <td>{{ pesanan.jumlah }}</td>
            <td>{{ pesanan.tanggal_pengiriman}}</td>
            <td>{{ pesanan.transportir}}</td>
          </tr>
          {% endfor %}
        </tbody>
        
      </table>
</div>
{% endblock%}

pemesanan/templates/navbar2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    {% block title %}

    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm p-3 mb-5" id="navigation" style='background-color: white;'>
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'Pertamina_Logo.png' %}" alt="" id="logo" style="height: 50px;width: 200px;">
        </a>
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            <a class="nav-link nav-item"href="{% url 'pemesanan:pemesanan' %}">Form Pemesanan</a>
            <a class="nav-link nav-item"href="{% url 'pemesanan:lihatPemesanan' %}">Lihat Pemesanan</a>
            <a class="nav-link nav-item"href="{% url 'home:sign_out' %}">Sign Out</a>
            <a class="nav-link nav-item">Halo, akun {{ user.email }}</a>
        </div>
    </div>
    </nav>
{% block content %}


{% endblock %}
</body>



</html>

pemesanan/templates/pemesanan.html
{% extends 'navbar2.html' %}
{% load static %}
{% block title %}
<style>
    #pemesanan-container{
margin-top:100px; 
}

</style>
{% endblock %}
{% block content %}
<div id="pemesanan-container">
    <div class="row">
        <div class="col">
            <div style="margin-left: 50px;">
            <div id="signup-title">
                <h2>Form Pemesanan</h2>
            </div>
            <div>
                <h5>Silahkan isi data berikut sesuai dengan pesanan BBM anda</h5>
            </div>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <div id="signup-form">
                        <div class="form-group">
                            <label>Lokasi Pembelian</label>
                            <input class="form-control" id="id-name" type="text" name="lokasi" placeholder="Lokasi Pembelian" required>
                        </div>
                        <div class="form-group">
                            <label>Jumlah BBM (kl)</label>
                            <input class="form-control" id="id-email" type="Integer" name="jumlah" placeholder="Jumlah BBM" required>
                        </div>
                        <div class="form-group">
                            <label>Tanggal Pengiriman</label>
                            <input class="form-control" id="id-email" type="date" name="tanggal_pengiriman" value="{{value|date:'Y-m-d'}}"required>
                        </div>
                        <div class="form-group">
                            <label>Transportir</label>
                            <input class="form-control" id="id-password" type="text" name="transportir" placeholder="Transportir" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            </div>
            
        </div>
        <div class="col">
          <img src="{% static 'kilang2.jpeg' %}" style="height: 100%;width:100%;">
        </div>
      </div>
    </div>
</div>
{% endblock%}